import comp_libs = libftxui%lib{ftxui-component}
import dom_libs  = libftxui%lib{ftxui-dom}

for example : component/cxx{*}
{
    n = component-$name($example)
    ./: exe{$n} $example $comp_libs
}

for example : dom/cxx{*}
{
    n = dom-$name($example)
    ./: exe{$n} $example $dom_libs dom/ixx{*}
}
