
# Public headers.
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{screen}: $pub/{$pub_hdrs}
lib{screen}: ftxui/screen/{hxx cxx}{* -*_test -*_fuzzer}

dom_libs = lib{screen}
lib{dom}: $pub/{$pub_hdrs}
lib{dom}: ftxui/dom/{hxx cxx}{* -*_test -*_fuzzer}
lib{dom}: $dom_libs

component_libs = lib{dom}
lib{component}: $pub/{$pub_hdrs}
lib{component}: ftxui/component/{hxx cxx}{* -*_test -*_fuzzer}
lib{component}: $component_libs

./: lib{screen} lib{dom} lib{component}

platform_poptions = # Platform specific poptions.
switch $cxx.target.class
{
    case 'windows'
    {
        src_inc_dirs += windows/
        if ($cxx.target.system != 'mingw32')
        {
            platform_poptions += -D_CRT_SECURE_NO_WARNINGS
        }
    }
    default
    {
		platform_poptions += -pthread
    }
}

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions += "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                $platform_poptions

# Export options.
lib{screen}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
}

lib{dom}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $dom_libs
}

lib{component}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $component_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
{
  lib{screen}: bin.lib.version = "-$version.project_id"
  lib{dom}: bin.lib.version = "-$version.project_id"
  lib{component}: bin.lib.version = "-$version.project_id"
}
else
{
  lib{screen}: bin.lib.version = "-$version.major.$version.minor"
  lib{dom}: bin.lib.version = "-$version.major.$version.minor"
  lib{component}: bin.lib.version = "-$version.major.$version.minor"
}

# Don't install private headers.
{hxx ixx}{*}: install = false
