import impl_libs = gtest%lib{gtest}
import impl_libs += libftxui%lib{ftxui-screen}
import impl_libs += libftxui%lib{ftxui-dom}
import impl_libs += libftxui%lib{ftxui-component}

lib{ftxui-tests}: {hxx cxx}{*_test}
lib{ftxui-tests}: $impl_libs

# Don't install private headers.
{hxx ixx}{*}: install = false
